In [1]:
import numpy as np

In [2]:
array_500x500 = np.zeros((500, 500))
#this shows a 2 dimensional array with 500 cells in each direction

In [6]:
print(array_500x500)
#printing array automatically makes them floats 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
pixel_edge_length = 15 #microns
pixel_center = (pixel_edge_length / 2)
#center of each pixel will be: [0, 0] +7.5 microns x +7.5 microns starting from bottom left corner of pixel

def calculate_center_of_pixel(pixel_edge_length, pixel_position, i = 0, j = 0):
#somehow call array[] multiple times with i,j inputs and every time the statement runs
#so it can tell us the center of each pixel
#i= the row value of pixel
#j= the columns value of pixel
#horz_d= horizontal distance from bottom left
#vert_d= vertical distance from bottom left
    
    
    
    """This print bellow is meant to take the input for"""
    print("for pixel [" + str(i) + ", " + str(j) + "] center of pixel is located" + str(horz_d) + " microns from left and " + str(vert_d) + "microns from top")
    